# from .fitter_dsps import (FILENAME_SSP_DATA, FULLFILENAME_SSP_DATA, SSP_DATA,
#                            _get_package_dir, get_infos_comb, get_infos_mag,
#                            get_infos_spec, lik_comb, lik_mag,
#                            lik_normspec_from_mag, lik_spec, lik_spec_from_mag,
#                            lik_ugri, mean_mags, mean_sfr, mean_spectrum,
#                            mean_ugri, ssp_spectrum_fromparam)
# from .fit_utils import (plot_fit_ssp_photometry,
#                          plot_fit_ssp_spectrophotometry,
#                          plot_fit_ssp_spectrophotometry_sl,
#                          plot_fit_ssp_spectroscopy, plot_fit_ssp_ugri,
#                          plot_params_kde, plot_SFH, rescale_photometry,
#                          rescale_spectroscopy, rescale_starlight_inrangefors2)
# from .met_weights_age_dep import calc_rest_sed_sfh_table_lognormal_mdf_agedep
from .dsps_params import SSPParametersFit, paramslist_to_dict
from .fit_filters import FilterInfo
from .fit_loop import (
    filter_tags,
    fit_bootstrap,
    fit_loop,
    has_redshift,
    make_bootstrap_plot,
    make_fit_plots,
    prepare_bootstrap_dict,
    prepare_data_dict,
)
from .fit_utils import plot_bootstrap_ssp_spectrophotometry, plot_fit_ssp_spectrophotometry, plot_fit_ssp_spectroscopy, plot_input_spectrophotometry, plot_SFH, plot_SFH_bootstrap
from .fit_vmap import (
    calc_eqw,
    fit_treemap,
    fit_vmap,
    istuple,
    lik_colr,
    lik_mag,
    lik_mag_rew,
    lik_rew,
    mean_colors,
    mean_mags,
    mean_sfr,
    mean_spectrum,
    readVmapFitsFromHDF5,
    red_chi2,
    ssp_spectrum_fromparam,
    vmap_calc_eqw,
    vmap_calc_obs_mag,
    vmap_fit_mags,
    vmap_fit_mags_rews,
    vmap_fit_rews,
    vmap_mean_colors,
    vmap_mean_mags,
    vmap_mean_sfr,
    vmap_mean_spectrum,
    vmapFitsToHDF5,
)
from .fitter_dsps import load_ssp, mean_lines
from .write_fsps_data_to_disk import write_fsps_data

__all__ = [
    "FilterInfo",
    "paramslist_to_dict",
    "SSPParametersFit",
    "plot_SFH",
    "plot_SFH_bootstrap",
    "lik_mag",
    "ssp_spectrum_fromparam",
    "mean_mags",
    "mean_colors",
    "mean_sfr",
    "mean_spectrum",
    "mean_lines",
    "calc_eqw",
    "lik_colr",
    "lik_rew",
    "lik_mag_rew",
    "load_ssp",
    "plot_fit_ssp_spectroscopy",
    "plot_fit_ssp_spectrophotometry",
    "plot_bootstrap_ssp_spectrophotometry",
    "plot_input_spectrophotometry",
    "fit_vmap",
    "fit_treemap",
    "filter_tags",
    "has_redshift",
    "prepare_data_dict",
    "prepare_bootstrap_dict",
    "fit_loop",
    "fit_bootstrap",
    "make_fit_plots",
    "make_bootstrap_plot",
    "readVmapFitsFromHDF5",
    "red_chi2",
    "vmap_calc_eqw",
    "vmap_calc_obs_mag",
    "vmap_fit_mags",
    "vmap_fit_mags_rews",
    "vmap_fit_rews",
    "vmap_mean_colors",
    "vmap_mean_mags",
    "vmap_mean_sfr",
    "vmap_mean_spectrum",
    "vmapFitsToHDF5",
    "write_fsps_data",
    "istuple",
]

"""
__all__ = ["_get_package_dir",
           "FILENAME_SSP_DATA",
           "FULLFILENAME_SSP_DATA",
           "SSP_DATA",
           "mean_ugri_sedpy",
           "lik_ugri_sedpy",
           "lik_comb", "lik_spec_from_mag", "lik_normspec_from_mag",
           "get_infos_spec","get_infos_mag","get_infos_comb",
           "rescale_photometry",
           "rescale_spectroscopy",
           "rescale_starlight_inrangefors2",
           "plot_fit_ssp_photometry",
           "plot_fit_ssp_spectrophotometry_sl",
           "plot_params_kde",
           "calc_rest_sed_sfh_table_lognormal_mdf_agedep"] #,
           #"PARAM_SIMLAW_NODUST","PARAM_SIMLAW_WITHDUST",
           #"PARAM_NAMES","PARAM_VAL","PARAM_MIN","PARAM_MAX",
           #"PARAM_SIGMA","galaxymodel_nodust_av","galaxymodel_nodust",
           #"galaxymodel_withdust_av","galaxymodel_withdust"
           #]
"""
